### ISSUE TITLE
Invalid URL in API description

### ISSUE THREAD

**Issue by IvanGoncharov** [amardeshbd/medium-api-specification#12]
Thank you for excellent spec 👍
I found just one minor issue: 
https://medium.com/developers URL on [line #9](https://github.com/amardeshbd/medium-api-specification/blob/master/medium-api-specification.yaml#L9) produce 404.

Also, you can duplicate https://github.com/Medium/medium-api-docs in `externalDocs` section.
Like I did in patch for your spec: https://github.com/APIs-guru/api-models/blob/master/APIs/medium.com/patch.yaml#L1-L2

**Comment by hossain-khan** [comment]
Thanks @IvanGoncharov for testing this and reporting it.
That URL used to work, because https://medium.com/developers/welcome-to-the-medium-api-3418f956552 redirects to https://medium.com/blog/welcome-to-the-medium-api-3418f956552, but unfortunately `https://medium.com/developers` doesn't redirect to `https://medium.com/blog` 😞 

I've updated the link with the blog URL instead 😄
